### ISSUE TITLE
Why 5 calls

### ISSUE THREAD

**Issue by joshfeingold** [5calls/5calls#123]
As a non-political guy I guess I find the name confusing.

Well, not the name, but the explaination of the name, really.

"Spend 5 minutes, make 5 calls."

For all my issues only my senators are listed.  

Now if what you mean is that with 5 calls you can call your two senators, representative, gov and pres, then we should say that.  Basically, I'm suggesting that you explain things such as:

Spend 5 minutes, make no more than 5 calls, have your voice heard.

**Comment by nickoneill** [comment]
Yep, we know there's a slight disconnect there. We've been positioning this as "pick as many calls as you're comfortable with, 5 is our suggestion" which is why we use language such as "what's important to you?" above the issues list.

I think the purpose is clear enough though, even if it doesn't rationally connect perfectly.
