### ISSUE TITLE
Support Safari 9

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#197]
Looks like Safari 9 is missing the `toLocaleString` feature we use to format our numbers nicely. It has roughly 50k views in the last month so it would be nice to support this browser version. Tests are already in place, just need to figure out if there's a polyfill or something we can use here.

**Comment by oderby** [comment]
Seems like https://github.com/andyearnshaw/Intl.js is a good candidate polyfill to use. A full list of possible polyfills can be found at http://jsi18n.com/

Looking at the README for Intl.js I'm left wondering how we should actually use it...the package author asserts ("Don't require polyfills in your modules, that's an anti-pattern. Your modules should assume that the runtime is patched (when needed), and that should be part of the contract.")[http://stackoverflow.com/a/28965677/7542666]. Which suggests that we should simply include `<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>` in the header of our index.html, but that wouldn't help with tests because our current karma config doesn't load index.html.

All that is to say, this seems to be more complicated than initial inspection suggests. So, here's a set of questions for the collective audience here:

1. Do we know if there are any other issues (locale-related or otherwise) with 5calls on Safari 9? We only discovered this due to adding a unit test elucidating the issue. Does anyone have access to Safari 9 and can manually test out the site? 
2. Is the complexity of conditionally loading a polyfill for this (and possibly other issues) worth it? That is, if this is the only problem on Safari 9, can we just manually implement the behavior in the component?
3. An alternative is to just always load the polyfill - how bad would that be?
4. I don't really understand how locales work - can we get away with only using 'en' locale for all users? Or is the point that we need to load different locales based on the user's locale preferences?
5. Finally, if we decide we need to load the polyfill, we need to figure out how to do it such that it's present in both the actual application in the browser as well as the test environment. Preferably we'd do this in a single way for both (that is, an easy, but bad, way to do this is to just manually inject it as a dependency for the test environment, separate from how it's loaded into the browser for users).

**Comment by nickoneill** [comment]
It definitely doesn't format the numbers properly on Safari 9, but it doesn't look like it breaks the site as a whole either. I don't think it's worth putting the time in if we don't absolutely need something like this. Agree @oderby ?

**Comment by oderby** [comment]
yeah, that was my point with question 1 - if we don't see any other issues, I'd vote we somehow just indicate that the 'format numbers properly' test is expected to fail (or write a test that asserts it behaves as expected on Safari 9) and go on with our lives. Alternatively, which may be easier to implmeent, is we just hardcode a fix/workaround for this particular issue into the component.

**Comment by nickoneill** [comment]
Yep, agreed. Can you handle that failure in the Safari 9 tests @oderby?
