### ISSUE TITLE
Add Selenium end-to-end tests

### ISSUE THREAD

**Issue by cdoremus** [5calls/5calls#207]
I propose adding end-to-end (e2e) testing to the web application using Selenium as an integration test harness. Tests will be written using the Selenium Webdriver JavaScript API in Mocha and Chai.

I have put together a branch containing a working prototype with a simple e2e test to get things going. The tests have been configured to be executed with the web application running locally. If we are going to want to run the e2e tests in CircleCI or Sauce Labs, I will need some help.

My prototype has end-to-end tests in a ```e2e-tests``` folder at the project root.

Comments/suggestions are welcome.

**Comment by oderby** [comment]
I've only had limited experience writing e2e tests for the browser, but in those cases we've used selenium with some success, and I know we've gotten it working with sauce labs, so it's at least possible. So, I'm supportive of using selenium. I expect @Mr0grog might have more to say on this topic though.

Also, @cdoremus do you want to push up your branch so others can review and chime in?

**Comment by Mr0grog** [comment]
👍 Selenium is generally the way I’d go with this. @cdoremus it looks like you may not have pushed your branch up; I don’t see it here or in your fork on Github.

Since I can’t see your branch I don’t know exactly how you’ve set it up, but have you used [webdriverio](http://webdriver.io)? It is a really nice wrapper around the somewhat-painful Selenium Webdriver API. I’ve generally had good experience with it and it includes support for managing tests against an array of browsers pretty much out of the box (via Sauce or any old Selenium Grid server).

**Comment by cdoremus** [comment]
@oderby and @Mr0grog, thanks for your feedback. I had a PR almost ready to go with npm scripts to boot up the front and back end before the tests were run, but they need to be changed now that the back end is in a private repo. I will talk to @nickoneill about how to handle this because everyone who wants to run these Selenium tests will need to be able to run the back end.

@Mr0grog, I just used the generic Selenium Webdriver API. We can discuss changing it to webdriverio after I push the PR.

**Comment by oderby** [comment]
I think with the change, we should actually consider not depending on the
dev version of backend, and just running code against deployed backend. I
generally find this annoying, as your tests can break underneath you due to
changes in deployed server that aren't communicated/deployed, but given
that this is a volunteer project and not under any real time crunch, this
would actually be an effective canary, in that we'd see our PRs/CI fail if
a breaking change is pushed to production without fixing it in the frontend.

**Comment by nickoneill** [comment]
Running these against the production backend is the right way to go. There's no reason someone should need to install Go (which isn't always trivial) to work on or test the frontend.

If we need a switch to turn off counting certain requests, we can do that. But I don't think it's a meaningful number of requests in the grand scheme.

**Comment by cdoremus** [comment]
My PR #209 runs the e2e tests using the local webserver and the production back end.
