### ISSUE TITLE
Decide on a frontend upgrade path

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#260]
Now that [choo v5 is out](https://github.com/yoshuawuyts/choo) (and significantly different than v4), we need to make a decision on what direction we're going with the frontend.

We've had plenty of problems with choo thusfar, particularly related to supporting types of features that aren't important to a small team with limited real world use cases, such as localization.

Options off the top of my head (there may be more):

1. Continue using choo v4 for the foreseeable future, accept the limitations behind this
2. Upgrade to choo v5 with major API changes (supposedly "the last API change")
3. Convert to some other frontend framework that fits our needs

This conversation will be a long one, so let's get started thinking about what makes the most sense for us and what timescale we need for implementation.

**Comment by schraj** [comment]
Some initial thoughts:

1) Continuing on v4 does not seem like a good option.  My main reason for saying this is that the documentation is no longer  current.  When a new person comes to work on the 5calls site, they will need to get up to speed on choo.  When they go to the look at the documentation, it is at v5, even now.  You have to go back into Git history to see v4 documentation.  The handbook is currently being updated to deal with v5 as well.  

2) As Nick says, there are significant downsides to the idiosyncracies of how Choo works and that won't change in v5.  Having just implemented the Localization on top of it, I can attest to the fact that it was more complicated that it should have been.

3)  The site is not too complex at this point.  Migration to another framework would probably not be a huge task.  Also, hopefully, 5Calls will continue to add functionality and so will become more complex.  If migration is considered a probability, sooner is better.

4)  It is probably too soon to start throwing out alternative frameworks.  But I will anyway : )  I'm a big fan of React/Redux and I see a lot of positives to moving to that framework.  The question here would be does it make it harder for people to work on the site than with choo?  Not sure about that one.  Choo is simple but most people are probably coming to it for the first time.  React/Redux is definitely more complex but there is a lot more documentation/samples and more people will already have had experience with it.

Angular(2) does not seem like a good fit for this project because it forces people to use typescript and that raises the bar for volunteers.

**Comment by nickoneill** [comment]
Thanks @schraj, those are some good points :) More thoughts and schedule on this will come this weekend.

There's a 4th option here as well: we could publish dynamic pages with the go backend and mostly ignore frontend javascript. At that point we could probably split the API server out from the router/page server.

**Comment by oderby** [comment]
Just to play a bit of devil's advocate - if we are explicit and clear that we're still using Choo v4 and link to the appropriate documentation ([repo](https://github.com/yoshuawuyts/choo/tree/6fc525fe05b065cd156c669bf9c1e055ee31368e), [handbook](https://github.com/yoshuawuyts/choo-handbook/tree/78f51fb26823a202c3c80af3bfd007807bafcd26)), it's actually the exact same situation as we are in now (because source code and his limited Readme are all the help I've ever found when looking to figure out Cho). So I don't think staying on v4 for a while longer will be any more onerous than it has been, for existing or new contributors. 

I make that point, because I think that, if we decide to migrate off v4 (whether that's onto v5 or another framework entirely), it should be done in parallel to continued usage and development of the v4 branch. That is, migration should be worked on a branch, while new feature development continues on master. Work on the migration should not block new features. At some point, we may need to freeze PRs for a short period of time while we merge the branch to master when it's ready, but that's all.

Agreed that Choo is overly complicated for what it does, and v5 looks like it only got worse. I want to do more research (and probably need to wait for them to actually update the handbook/provide more examples), but from the one [example](https://github.com/yoshuawuyts/choo/blob/96c0d1bc29e73ab734d198a459a098feb12fd469/example/index.js) using v5 I can find so far, I think I'd prefer staying on v4 to migrating to v5. But I'm probably even more interested in migrating off Choo entirely...

**Comment by cdoremus** [comment]
@nickoneill  I've talk to you privately about this, but for the record I think that moving to React/Redux seems to be about the same amount of effort as upgrading to Choo 5. It seems that React is more of a fit to Choo code than Angular. I'm not sure about other frontend frameworks. Choo documentation and resources are limited as are the number of people having experience with the framework. React does not have that problem, which will make recruiting and onboarding new people easier.

I think there are a lot of benefits to adding optional static typing using TypeScript or Flow. I personally am a fan of TypeScript, which appears to be catching on with JavaScript developers.

I agree with @oderby that we need to continue development in Choo v4 for the time being and do any upgrade or migration in a separate branch.

**Comment by schraj** [comment]
@oderby True that we can link to the appropriate documentation so that becomes less of an issue.

**Comment by greggraf** [comment]
**effort**
I don't know how I feel about upgrading to Choo 5, but to get a sense of the upgrade effort  I created a branch.  It works for me to the extent that I have tested. I am curious to see how it works against the e2e tests.
  https://github.com/5calls/5calls/compare/master...greggraf:choo5

**option 4**
I am intrigued by option 4.

> There's a 4th option here as well: we could publish dynamic pages with the go backend and mostly ignore frontend javascript. At that point we could probably split the API server out from the router/page server.

The app could benefit from being treated like a site in terms of SEO. But even with this approach, the JS framework question comes up. 

**Choo**
Choo is awesome because it lacks lots of the overhead of React/Babel/Angular/WebPack/Fatigue.

Its not so awesome in that it lacks maturity (and therefore lacks helpful resources and existing code samples and ways of doing things.) And, the total API about face from v4 to v5 was unnerving.

**so....**
I guess I would ask: what are the current needs for the app/site? Up until now, its mostly about 

- rendering markup from JSON,
- some ajax
- interacting with LocalStorage. 
- internationalization

I don't mean to imply that it won't become more complicated, but it probably won't become complicated like a CMS front end.

The choice of front end should lean toward the smallest overhead for solving the problems presented by the application. 

Staying with what is currently there gives us the room to improve unit tests, end to end tests, possibly refactoring/simplifying and tightening the existing code.

(Lot of thoughts, no actual recommendation.)

**Comment by schraj** [comment]
As an exercise, I migrated a majority of the site to React-Redux:
https://github.com/schraj/react-5calls

Choo maps pretty closely to react-redux so it wasn't too bad.

The following things are not touched:
1) I'm not posting to the 5Calls backend.  I am using the data coming from the backend in the same way that the existing app does.
2) I haven't integrated the geolocation.
3) No tests
4) code is in draft form.  Basically proof of concept.

To run it:
`npm install`
`npm start`

Let me know if you try it and it doesn't run.

No problem at all if we don't go in this direction, I was just curious what it would look like.  Maybe it can inform the discussion about upgrade options.

**Comment by nickoneill** [comment]
@greggraf the conversion to v5 doesn't seem as crazy as I thought it would, so it's good to know we could upgrade there if we decide to stick with choo. I'm concerned about the constant API changes but otherwise it's done the job pretty well... feel free to point out any more downsides with choo.

I'm interested in this backend page-building as well. I don't think it will remove the requirement that we have a frontend js framework, but perhaps we break up the components more sensibly. The backend is responsible for issue data and the frontend is responsible for layering in the contacts and interacting with the page (for example).

@schraj I'm super impressed with this conversion! I don't have a working knowledge of react but I can sort of see how it compares by looking how the components are set up. It doesn't seem simple to do this translation so I appreciate the effort here to figure out if it's the right solution.

My biggest concern so far is the size of the `bundle.js` with react, a whopping 1.7MB just to start loading the page content. I sort of understood the stated benefit of choo in this regard when using it, but this really drives the point home. It also feels more complex to do the same things we're doing right now but this may be my increasing familiarity with choo and lack of the same with react.

---

As for goals going forward, we do have a fairly simplistic model as described by @greggraf. There's no big changes for what we're going to use the frontend for in the near future. Maybe some improved design and having a logged-in user accounts would be the biggest changes I see right now and that's just more of the same thing we have today.

Feel free to weigh in on thoughts again. Let's plan on making a decision on this in the next week.

**Comment by nickoneill** [comment]
Two more quick callouts:

@oderby: In agreement for choo being complicated. We haven't really looked (I don't know know the field all that well) into things less-complicated than react/angular/choo but I would be interested in a suggestion here.

@cdoremus: I'm also a fan of better typing for javascript. A bit hesitant to combine complex systems if we want to use it with something nascent like choo as opposed to something more proven like react but whatever we jump to, investigating compatibility for typescript or coffeescript or whatever to speed up development would be a nice bonus.

**Comment by schraj** [comment]
@nickoneill You gave me a shock there : )

That was the dev build.  The production build bundle weighs in at 295k.

The next easy optimization would be moving to "Preact" which should handle everything that this app needs to do and is supposed to be faster and bring the bundle size down by maybe another third.
https://medium.com/@rajaraodv/using-preact-instead-of-react-70f40f53107c

**Comment by nickoneill** [comment]
Ah, ok!

Interesting with preact - I was going to suggest that we sort of get stuck in this whole choo business again with something not quite main stream but since the API is the same as React, we can always bail back to React with little effort. Sounds like this could be a good option.

**Comment by schraj** [comment]
I looked a little deeper into Preact to see what you give up in exchange for reduced size/increased speed.

It appears that the only substantial omission from Preact currently is "Synthetic Events"(React wraps browser events in a standardized "SyntheticEvent" object- https://facebook.github.io/react/docs/events.html).  However, they are essential only for compatibility back to IE8 and before.  I expect that they may add value for apps that have very complex interactions as well, though I haven't run into their specific benefits.

https://preactjs.com/guide/differences-to-react
https://preactjs.com/about/browser-support

Another potential issue is how Preact's development tracks with that of React.  That is, when React features are added, does Preact lag behind in adding these as time goes on.  The Preact project seems dependent on 1 particular individual.  As @nickoneill points out, having the ability to fall back to react would be important and so sticking with the "compatibility mode" and the "preact-compat" setting would make sense.  

A contrary thought: Preact gains us 90k, which is not insignificant. However, if React/Preact were the direction pursued, there would also be benefits to accepting that overhead for the sake of being within the mainstream of the larger React development stream.

**Comment by cdoremus** [comment]
@nickoneill as a proof-of-concept I created a branch using TypeScript for the e2e tests and pushed it here: https://github.com/cdoremus/5calls/tree/e2e-tests-typescript. Only files in the e2e-tests folder were converted to TypeScript. The TypeScript allowed code-completion of the `webdriverjs` API, which isn't well documented. It also helped me discover a couple of small errors that I will be submitting as a PR sometimes soon.

TypeScript is built on top of JavaScript and not a separate language like CoffeeScript that gets compiled to JS. Look inside the files and you will see ES 6 code. TS adds _optional_ type annotations that I have used sparingly in the code.

As I mentioned to you on Slack, I'm not sure if TypeScript will be very helpful with our Choo code since there are no available type declarations for the Choo framework, but it is something that could be helpful if we go forward with React.

**Comment by nickoneill** [comment]
Very interesting @cdoremus! What do you use to see these types? Some IDE that supports autocompletion? I don't know a lot about development tools for this angle of modern javascript.

@schraj Browser support without synthetic events seems pretty similar to what we aim to support today (unofficially, but essentially what we've focused our testing on) so I don't think losing IE 8/9 is a big deal. I'm really quite surprised React is even concerned with it.

I'm fairly confident that going with React via Preact is the right way to go here. I know we've focused so far on straight ports to get examples of what this could look like going but I'm guessing there's architectural tweaks that might make this easier to deal with in the future. Do you both @schraj / @cdoremus want to work together to come up with a proposal for any changes + supporting typescript and moving forward with this?

(@greggraf I don't think this change would prevent us from moving forward on with a model with includes details from "option 4". Moving entirely to Go-built pages doesn't seem to make sense given our existing experience, and the improvements in some prebuilt parts of pages feel like an optimization we can tackle afterwards)

**Comment by oderby** [comment]
@nickoneill I think most people use [Visual Studio Code](https://code.visualstudio.com/) with typescript, although I'm sure most editors support it as well.

I agree that Preact seems like a good direction to go in. Also agreed that we should take this opportunity to consider some re-architecture of the app data flow to fit better to both our current/future needs and the react model. 

Although I'm intrigued by TypeScript, I'm not convinced that the static typing/analysis benefits are worth the overhead of not using pure JS (although it's 1000x better than using CoffeeScript, so very glad we're not considering that) and the intimidation factor that might deter new developers from getting involved in the project. That said, I definitely encourage the proposal to address these concerns and lay out the pros/cons for switching to TypeScript, and what that switch would look like.

**Comment by schraj** [comment]
Sure.  Will touch base with @cdoremus on working out a proposal.

**Comment by nickoneill** [comment]
Made this decision!
