### ISSUE TITLE
Configure E2E tests to run in CircleCI and SauceLabs

### ISSUE THREAD

**Issue by cdoremus** [5calls/5calls#291]
Now that we have the suite of end-to-end tests in #252 merged into master, we need to configure CircleCI and SauceLabs to run these tests. Rob (@Mr0grog) has kindly agreed to lead this effort.

**Comment by oderby** [comment]
*ping* Is there any work in progress or planned work on this front?

**Comment by Mr0grog** [comment]
Yes! I’m sorry I have taken so long to get to this. I got a proof of concept running earlier this week, but have not had a chance to circle back and clean it up yet, which is why I haven’t posted a PR: https://github.com/Mr0grog/5calls/tree/291-run-these-tests-all-the-way-from-here-to-there-but-do-the-job-from-some-other-place-altogether

I’m a little worried that part of doing this right—Sauce Connect tunneling, running the tests in multiple browsers—means re-implementing a big part of webdriver.io (but not as well, since we aren’t dedicated to it). On the other hand, switching probably means rewriting all the browser commands in the existing end-to-end tests.

**Comment by Mr0grog** [comment]
Also, totally happy to create a work-in-progress PR with what’s done now, if that would be helpful.

**Comment by oderby** [comment]
Hmm, I see. Well, I'm not a fan of rewriting all the browser commands, unless there's some other benefits to doing that?

Is there some way we could just use https://github.com/webdriverio/wdio-sauce-service without using the rest of webdriver.io?

**Comment by nickoneill** [comment]
We recently were approved for a browserstack sponsored account and can run e2e tests across a large number of browser combinations. It would be nice to get an e2e test running here for basic functionality so we can ensure support going forward!

**Comment by Mr0grog** [comment]
@nickoneill Do you still need someone to work on this? Sorry I have not had much time lately; I’m hoping I might have a few good hours to dedicate to this over the weekend if needed.

**Comment by nickoneill** [comment]
@Mr0grog We did end up writing some new e2e tests (see the testcafe section in the readme for running) but I didn't see an obvious way we could get them to run on PRs. Browserstack is happy to run them as much as we want, but where would we run a dev server that browserstack could run its tests against?

I'd love to know if there's an easy solution to this (i.e. some part of our existing CI flow can build and then kick off browserstack tests)... netlify hosts the site now and can be configured to do preview builds for every PR if that might be helpful?

**Comment by Mr0grog** [comment]
Well, that took quite a bit longer than expected, but not because of anything with Browserstack or CircleCI :P
