### ISSUE TITLE
Support switching languages in UI

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#303]
Now that we support spanish in the UI, we should provide a toggle to manually set the language rather than exclusively relying on browser language which might not accurately represent the language desired.

**Comment by oderby** [comment]
Per conversation in slack, it would be nice to report language choice statistics to our Google Analytics account, so we can better understand the language breakdown of our users. Here are the directions to do so via @nickoneill 

> I just set up a custom dimension 
>```javascript
>var dimensionValue = 'SOME_DIMENSION_VALUE';
> ga('set', 'dimension3', dimensionValue);
>```
> Keep `dimension3`, set the value to something to uniquely identify the language

@greggraf I think it'd make sense to include this in #312, but wanted to get your thoughts before increasing the scope of that work.

**Comment by greggraf** [comment]
It is pretty easy to set that when the language is changed.
And when the app starts up, it can be set to the default or what was pulled from localStorage.

Both of those occur after the Google Analytics library has loaded and the first calls from the html page have already been queued up and sent off.

This means the initial calls will *not* have the 'dimension3' set, but further reporting calls from within the app will (such as navigating to issue pages or indicating the results of calls).

It is a little trickier to get that information into the initial calls from the html page. The app does the work to extract the localStorage value or set the default, but the html page does not have this information when its loading the Google Analytics library and queuing up the reporting calls.

I will put together a commit that makes the post app loading reporting calls have this value and if its worth pursing I will explore getting that value out to the other calls.

**Comment by greggraf** [comment]
ok, i have the following approach:

https://github.com/5calls/5calls/pull/312/files#diff-93471d4bf84d0569fadcebe5fba72773R89
In the initial execution of `main.js` after determining the `cachedUserLocale` from either `localStorage` or the `i18n.js` library, store that value in the `userLocale` property on the `window` object.

https://github.com/5calls/5calls/pull/312/files#diff-0a3e976c1c22ad5508a7403949f5faf9R115
In `index.html`, during the Google Analytics code, check if `userLocale` has been set on the `window` object, set it to the `dimension3` value after creating the Google Analytics instance, but before sending the pageview call.

The check for `userLocale` is there in case the code determining `cachedUserLocale` has not finished or fails before the Google Analytics sends the pageview call.

https://github.com/5calls/5calls/pull/312/files#diff-93471d4bf84d0569fadcebe5fba72773R262
In `main.js` the `languageChanged` effect sets `dimension3` to the value that it has been changed to so that it is updated as the user navigates the application.

**Comment by nickoneill** [comment]
Post-app loading should be fine, I set this as a session-level dimension so it will apply back to all previous events in this session.
