### ISSUE TITLE
Add circular progress indicator for issue completion

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#387]
Some folks can't call everyone at once, others only call a smaller selection of reps than what we send. It would be useful to provide a progress circle to let people know how far along they are if they haven't completed their reps.

Background in https://github.com/5calls/ios/issues/207

**Comment by nickoneill** [comment]
One more thing: since we're adding more information here, we can default to not marking the issue as completed if "skip" is used, like it behaves on other platforms.

**Comment by benjamincarp** [comment]
Is there a mockup of what you would like this to look like or should contributors just try to get as close to the look this feature in iOS as possible? (If you have screenshots of current iOS state that would be helpful for Android users like myself as well.)

**Comment by nickoneill** [comment]
Actually it looks like this is already complete, see the semi circle in the partially called issue:

![image](https://user-imagBBC es.githubusercontent.com/49688/84729055-97a60480-af47-11ea-8e75-6f2cb8ba1e9d.jpeg)

**Comment by benjamincarp** [comment]
I just noticed another related bug. If I have not completed a task and I refresh, the active contact goes back to the first contact rather than the first incomplete contact. 

<img width="833" alt="Screen Shot 2020-06-17 at 3 35 40 PM" src="https://user-images.githubusercontent.com/7663672/84947812-7d3b6a80-b0b0-11ea-9eff-4053043a8cf9.png">

It seems to me that the way the data is stored makes calculating how many/which contacts are complete inside an issue somewhat intensive. Does the list of contacts on a single issue change over time in some cases? If so, are they only additions or occasionally removals? Trying to make sure I don't overbuild for theoretical use cases.

**Comment by nickoneill** [comment]
The contact list for an issue occasionally changes, such as when specific legislation that we are pushing in both House and Senate passes one chamber (contact in that chamber is remove) and moves to the next and potentially back again.

I don't know what specifically you're referring to as being intensive (iterating through a whole list of calls made?) but these numbers only rarely get into the thousands for individual users so the time to iterate through them is always small, even if inefficient.

Still, open to changes if you see them, but I am very wary of changes to historical saved data if you're looking in that direction.

**Comment by benjamincarp** [comment]
What seems intensive is that as it is in redux each issue seems to only hold the groups of contacts (can these only be house, senate, or both so 1, 2, or 3 contacts per issue?), there is separate logic that parses the groups against the pool of contacts to see who fits in those groups for your location, then the list of folks you've contacted as a user is in a different data structure. 

In order to show progress on the sidebar for all issues without restructuring the model in redux for each issue you would first need to calculate the list of contacts then filter that list based on state.userstats.all to see how many of the folks you've contacted previously on this issue are still part of the contacts list. Doing that for every issue on every paint doesn't seem like the way to go, but I also am not familiar enough with this codebase yet to say exactly where these calculations and data points should live. 

Ideally I think I'd like to calculate the list of contacts for each issue right when the list is returned from the API and store that in redux along with a status for each contact and update those statuses anytime a contact event is recorded.
