### ISSUE TITLE
Multiple issue requests for team pages

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#407]
If you watch the network debugger when you load a team page (in cache or not), multiple requests are made in rapid succession for the list of issues from this team. Here's a screen:

<img width="1162" alt="screen shot 2018-07-14 at 1 12 04 pm" src="https://user-images.githubusercontent.com/49688/42728115-d6717dc0-8767-11e8-9076-5d5f283baa17.png">

We shouldn't be duplicating this request so much while loading.

@cdoremus not sure if you have time to check this out, but if you do please let me know!

**Comment by cdoremus** [comment]
I'd like to look at it, but I'm getting slammed at work lately, so I'll try to get to it when I can. If anyone else has cycles to work on it, be my guest.

**Comment by nickoneill** [comment]
No worries @cdoremus, thanks for letting me know!

**Comment by nabrahamson** [comment]
This is caused by the getGroupIssuesIfNeeded function. This gets called by the reducer in rapid succession before any of the network calls are resolved. 
To fix this, I will be adding a middleware that will give us an option to throttle our dispatch calls. 
https://www.npmjs.com/package/redux-throttle

**Comment by nickoneill** [comment]
What's different about this vs the one on the main page? We don't have this issue there. Are we calling this on the wrong lifecycle method?

**Comment by nickoneill** [comment]
removing teams so this can be closed
