### ISSUE TITLE
Script title replacements are no longer working?

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#512]
Previously our scripts replaced [REP / SEN NAME] with text such as "Senator Diane Feinstein" but it appears to now only be using "Diane Feinstein". Let's figure out what happened to the title replacements.

**Comment by thebrengun** [comment]
This is because the area in the contact is `US Senate` and `US House` not `House` nor `Senate`. I updated the Script component to check for US Senate and US House but left House and Senate as options as well so that cases which use those area names won't break. I updated the test as well to use US House and US Senate. https://github.com/5calls/5calls/pull/515

**Comment by nickoneill** [comment]
Thank you @thebrengun! This makes sense, I think the area names got more specific as we started supporting state representatives. Will merge this right away.
