### ISSUE TITLE
Add clarity on why ZIP may not return all your representatives?

### ISSUE THREAD

**Issue by flyingrat42** [5calls/5calls#64]
For "split" zip codes (like mine), the API appears to return only the Senators when only the ZIP is entered, because the full street address is needed to resolve my congressional district.  Can some language be provided on the location bar to clear this up so people don't wonder why they're not getting their Representative's contact info?

**Comment by nickoneill** [comment]
We return a `splitDistrict` value in the JSON, it's just up to the frontend to determine if that's true and prompt for a better locaiton

**Comment by oderby** [comment]
In case it helps, here's some sample copy (taken from [here](http://act.commoncause.org/site/PageNavigator/ElectedOfficials.html))
![split_zip_copy](https://cloud.githubusercontent.com/assets/1351158/22757261/fd2bf64c-edfe-11e6-93ff-f21f2bc5814b.png)
(Note: 94110 is not actually a split zip for federal reps, only at the local level, but you get the idea) It would be great if someone can provide a few examples of "split" zip codes for whoever fixes this to test with...

**Comment by oderby** [comment]
Is anyone working on this issue?

A user ran into this issue today, so recording what was found from that investigation:
Some test cases: 33408, 04103, 94043, 60647

It appears that even with more information, sometimes civic api doesn't give congressional information. An example is 33408-3231, for which [civic api](https://developers.google.com/apis-explorer/#p/civicinfo/v2/civicinfo.representatives.representativeInfoByAddress?address=33408-3231&levels=country&roles=legislatorLowerBody&_h=1&resource=%257B%250A%257D&) still doesn't list a congressional district, but the [government does](http://ziplook.house.gov/htbin/findrep?ZIP=33408-3231&Submit=FIND+YOUR+REP+BY+ZIP). I've submitted a bug report to them about this particular issue.

However, it's quite likely that other users will run into this issue, even if they put in a specific address. So we should consider this possibility when thinking through the messaging around possible failure cases.

**Comment by charkattack** [comment]
I'm getting a lot of emails about the split districts after the Michael Moore mention. Here are a few of them:
- My Zip code has multiple districts. Since your app doesn't go past the zip code level, I'm not sure if I am speaking to the correct representative's office.
- I put in my zip and it will not show my rep. I've in my location and can't see my reps 
- HELP!!!! Please fix the location service to allow those of us overseas or expats to manually record our address. My zip code has multiple representatives, and being overseas, I can't use the location services.
- Hello, thank you for the app. It doesn't pick up my correct location, as a result, I'm getting the wrong reps. Is there a way to enter in my correct address or district ?
- My zip code links me to the wrong representative. I am in zip code 60707. I live in Chicago , IL. Can you look into this for me? Thank you
- When I choose Location, it the app displays an incorrect address. Any way to enter my address manually?
- I set my zip as 20007 and the app tells me I'm in split jurisdiction. Same result if I used my location. Good luck fixing this. Thanks.
- When I enter my DC zip in the app (or any DC zip) it tells me I live in a split jurisdiction and should use the location feature - but I use that, and it doesn't work either. I can't really use the app until this gets fixed so I thought I'd bring it to your attention. It happened to me on the Russia Intelligence committee issue.

**Comment by nickoneill** [comment]
We made this more clear when you're in a split district in the react repo
