### ISSUE TITLE
Add link support to issue descriptions

### ISSUE THREAD

**Issue by bitwiseman** [5calls/5calls#76]
In this age of fake news and incendiary headlines, I'd like to be able to read source materials that support statements made in the descriptions.

**Comment by nickoneill** [comment]
Thanks @bitwiseman, totally agree and this is definitely planned

**Comment by nickoneill** [comment]
Previously: "Add citation lists to issue descriptions"

This is just a more general task to support links from the airtable when they're passed over from the backend.

**Comment by nickoneill** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support links from airtable text on the frontend](https://trello.com/c/KFlbtknl/43-support-links-from-airtable-text-on-the-frontend)

**Comment by nickoneill** [comment]
This could be proper links or some form of markdown support, whatever makes the most sense.

**Comment by samking** [comment]
I'll take a stab at this once I get a development environment set up.

**Comment by dektar** [comment]
It would be awesome to be able to do links on Android, too! But not all Android users will update their app versions, so not everyone will be able to support issues with markdown in the text.

Could this be released in a new version of the API (maybe &version=2) so that older versions of the apps can still access readable issues descriptions using the original URL?

**Comment by nickoneill** [comment]
Yes - I'm not sure we're quite ready for a v2 api but perhaps the field is `richReason` or `markedupReason` in addition to the existing `reason` field.

**Comment by samking** [comment]
Just to make sure I understand the above conversation:
1.  Right now, the server returns `reason` to all clients (Android, iOS, and web), and that is displayed in each frontend.
2.  App users might have a delay in updating, so we need to make sure that we don't disrupt the old method when implementing a new method.
3.  One way to do this might be to have the backend send both `reason` and `markedupReason` and then change https://github.com/5calls/5calls/blob/a7b3483af5befcf72d2a24d23ed013618c2a9068/static/js/components/call.js to use the `markedupReason`

Is that correct?

Assuming we do go with Markdown, one of the design principles of Markdown was that it should be readable regardless of whether it was rendered or plain text.  The plain text might look like:
```
I have a [link](http://website.com).  Maybe I have some *bold* too.  Or maybe I have a [reference][1].

...

[1]: http://other-website.com
```

Would it be worse if we started sending stuff like that to Android and iOS users who haven't updated their apps?  

The reason I ask is because, if we wanted to support both a plain text version as well as a rich version, folks would need to enter the same thing twice (once with Markdown and once without) in the Airtable, or we would need to re-render Markdown into plain text in the backend, which could have unintuitive side effects (eg, if we referenced a link in the prose but that link weren't available in the app, users would probably be confused and would report it as a bug).

**Comment by dektar** [comment]
The markup will be a poor user experience for users on old versions, at least in Android, because the links will not be clickable or copy-able. So they will see all these links they would *like* to click, but since the links are just text in a TextView, they can't do anything about it.

**Comment by nickoneill** [comment]
Yeah, I don't think we can deal with clients seeing raw markdown... well, at least in some cases. `*something emphasized*` is probably OK because some people use that in plain text normally. Either stripping the bracketed markdown characters (and link data) or rendering it to plaintext would be OK if we wanted a technical solution.

Alternatively, it might be fine to do manual markdown and non-markdown versions in airtable for a limited amount of time. I think we can get most people moved over in a reasonable amount of time. iOS has ~85% of people on the newest release roughly two weeks after it was sent out... give it four weeks and that's probably above 90%. Thoughts on that @dektar?

**Comment by dektar** [comment]
@nickoneill Unfortunately folks on Android upgrade more slowly -- I'm only at 72.19% on the latest version, which was launched April 5. Only 80% are on the previous two versions, with the remaining 20% spread across lots of old versions. (Active users is a better story, with 87% on the latest version... but it's still not super.)

I'd be uncomfortable giving any users a poor user experience by switching to use `markedupReason` by default, but I'd be happy to help build version numbers into the API so that we don't get hurt by this issue in the future.

One way to help them upgrade is, as soon as all clients can use the new `markedupReason`, to prefix each `reason` with `"Please upgrade the 5calls app"`.

Eventually, if we really need to deprecate the `reason` field, I suppose the `reason` could be:
`"Please upgrade the 5calls app\n\n" + markedupReason` (with some thoughts around localization). At that point the writers would no longer need to write two versions, but again, I'd be somewhat uncomfortable with this.

**Comment by samking** [comment]
So, it sounds like the best solution would be to have the AirTable be markup (to avoid double entry) and then render that as text on the backend for `reason` and let clients do what they want with `markedupReason` -- is that the consensus?

**Comment by nickoneill** [comment]
Yep, that's good @samking. That way we can support clients for as long as we need going forward without putting too much burden on the issue writing team.

I would note that the backend render -> plaintext doesn't have to be perfect, it just has to get the text to a point where it's not confusing to users. It may be easy to get "perfect" results but in the case that something easy only gets us to 90%, that's probably good enough. We can discuss how it looks here.

**Comment by oderby** [comment]
@samking I don't know how far you've gotten, but I've recently played around with the blackfriday markdown processor. It's a lightweight, feature-complete processor that I've enjoyed using. Just a recommendation if you haven't found a solution for that yet ;)
